# Generated by Django 6.0.1 on 2026-01-20 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Appointments",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=200)),
                ("mobile_number", models.CharField(max_length=10)),
                ("doctor", models.CharField(max_length=200)),
                ("date", models.DateField()),
                ("time", models.TimeField(auto_now_add=True)),
            ],
        ),
    ]
