# Generated by Django 5.2.7 on 2026-01-21 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointments",
            name="time",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
